development: &default
  default_twitter_handle: 'kleer_la'
  google_client_id: <%= ENV['TIL_OMNIAUTH_GOOGLE_KEY'] %>
  google_client_secret: <%= ENV['TIL_OMNIAUTH_GOOGLE_SECRET'] %>
  heroku_production_app_name: 'kl-ha'
  host: 'localhost'
  protocol: 'http://'
  permitted_domains: 'kleer.la'
  slack_post_endpoint:
  twitter_access_token:
  twitter_access_token_secret:
  twitter_consumer_key:
  twitter_consumer_secret:
  update_twitter_with_post: "false"

test:
  <<: *default

staging:
  <<: *default
  host: 'ha-staging.kleer.la'

production:
  <<: *default
  host: 'ha.kleer.la'
  permitted_domains: 'kleer.la'
